"""create_projects_table

Revision ID: 43e498743193
Revises: 
Create Date: 2026-07-24 13:06:46.165738

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43e498743193'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('preacher_name', sa.String(length=200), nullable=True),
    sa.Column('bible_reference', sa.String(length=200), nullable=True),
    sa.Column('church_name', sa.String(length=200), nullable=False),
    sa.Column('youtube_channel', sa.String(length=200), nullable=False),
    sa.Column('full_sermon_url', sa.String(length=500), nullable=True),
    sa.Column('video_filename', sa.String(length=255), nullable=True),
    sa.Column('cover_filename', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('fps', sa.Float(), nullable=True),
    sa.Column('video_codec', sa.String(length=64), nullable=True),
    sa.Column('audio_codec', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Enum('created', 'importing', 'ready', 'transcribing', 'analyzing', 'editing', 'rendering', 'completed', 'failed', name='project_status', native_enum=False, length=32), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('projects')
    # ### end Alembic commands ###
