"""create_transcripts_tables

Revision ID: 904cb8e88d3f
Revises: 43e498743193
Create Date: 2026-07-24 13:16:48.707348

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '904cb8e88d3f'
down_revision: str | None = '43e498743193'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transcripts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('source', sa.Enum('uploaded_srt', 'uploaded_vtt', 'uploaded_json', 'uploaded_txt', 'whisper', 'youtube', 'manual', name='transcript_source', native_enum=False, length=32), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=True),
    sa.Column('status', sa.Enum('ready', 'unsynced', 'failed', name='transcript_status', native_enum=False, length=32), nullable=False),
    sa.Column('full_text', sa.Text(), nullable=False),
    sa.Column('has_word_timestamps', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', name='uq_transcripts_project_id')
    )
    with op.batch_alter_table('transcripts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transcripts_project_id'), ['project_id'], unique=False)

    op.create_table('transcript_segments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('transcript_id', sa.Uuid(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('start_seconds', sa.Float(), nullable=True),
    sa.Column('end_seconds', sa.Float(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['transcript_id'], ['transcripts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transcript_segments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transcript_segments_transcript_id'), ['transcript_id'], unique=False)

    op.create_table('transcript_words',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('transcript_segment_id', sa.Uuid(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('start_seconds', sa.Float(), nullable=True),
    sa.Column('end_seconds', sa.Float(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['transcript_segment_id'], ['transcript_segments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transcript_words', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transcript_words_transcript_segment_id'), ['transcript_segment_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transcript_words', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transcript_words_transcript_segment_id'))

    op.drop_table('transcript_words')
    with op.batch_alter_table('transcript_segments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transcript_segments_transcript_id'))

    op.drop_table('transcript_segments')
    with op.batch_alter_table('transcripts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transcripts_project_id'))

    op.drop_table('transcripts')
    # ### end Alembic commands ###
